const setores = [
  { id: 1, nome: "Frigoríficos e Açougues", cat: "agro", tag: "Alíquota zero", resumo: "Carnes in natura com alíquota zero de IBS/CBS. Setor mais beneficiado. Crédito sobre despesas operacionais." },
  { id: 2, nome: "Autopeças", cat: "comercio", tag: "Impacto alto", resumo: "Fim do ICMS-ST e monofásico. Cada elo passa a pagar sobre a margem (~28%). Reajuste de preços necessário." },
  { id: 3, nome: "Farmácias e Drogarias", cat: "comercio", tag: "Misto", resumo: "Medicamentos especiais com alíquota zero; demais com redução de 60%. Ortopédicos e higiene menstrual zerados." },
  { id: 4, nome: "Bens Móveis Usados e Veículos", cat: "comercio", tag: "Específico", resumo: "Regras diferenciadas para veículos e bens usados. Impacto na margem e no crédito." },
  { id: 5, nome: "Supermercados", cat: "comercio", tag: "Cesta básica", resumo: "Cesta básica com alíquota zero. Demais alimentos com redução. Gestão de mix de produtos crítica." },
  { id: 6, nome: "E-commerce", cat: "comercio", tag: "Destino", resumo: "Tributação no destino e split payment impactam fortemente marketplaces e operações interestaduais." },
  { id: 7, nome: "Pet Shops", cat: "comercio", tag: "Padrão", resumo: "Produtos pet e serviços. Rações e alimentos pet com regras específicas. Crédito amplo sobre despesas." },
  { id: 8, nome: "Restaurantes, Bares e Lanchonetes", cat: "servicos", tag: "Serviços", resumo: "Alíquota padrão com crédito sobre insumos. Impacto na formação de preços e no Simples Nacional." },
  { id: 9, nome: "Hotelaria", cat: "servicos", tag: "Turismo", resumo: "Serviços de hospedagem. Possíveis regimes diferenciados e impacto no fluxo de caixa com split payment." },
  { id: 10, nome: "Saúde — Consultórios e Clínicas", cat: "saude", tag: "Redução 60%", resumo: "Serviços de saúde humana com redução de 60% na alíquota. Grande benefício para o setor." },
  { id: 11, nome: "Odontologia", cat: "saude", tag: "Redução 60%", resumo: "Serviços odontológicos com redução de 60%. Crédito sobre materiais e equipamentos." },
  { id: 12, nome: "Salões de Beleza", cat: "servicos", tag: "Padrão", resumo: "Serviços de beleza na alíquota padrão. Impacto no Simples e na competitividade." },
  { id: 13, nome: "Escolas e Instituições de Ensino", cat: "servicos", tag: "Redução 60%", resumo: "Educação com redução de 60%. Manutenção de acesso e impacto em mensalidades." },
  { id: 14, nome: "Infoprodutores", cat: "servicos", tag: "Digital", resumo: "Cursos online e produtos digitais. Tributação no destino e regras para plataformas." },
  { id: 15, nome: "Advocacia", cat: "servicos", tag: "Redução 30%", resumo: "Profissões intelectuais com redução de 30%. Impacto no honorário e no crédito de despesas." },
  { id: 16, nome: "Contabilidade", cat: "servicos", tag: "Redução 30%", resumo: "Serviços contábeis com redução de 30%. Oportunidade de reposicionamento estratégico." },
  { id: 17, nome: "Postos de Combustível", cat: "comercio", tag: "Monofásico", resumo: "Regime monofásico para combustíveis. IS sobre fósseis. Mudança estrutural na cadeia." },
  { id: 18, nome: "Setor Imobiliário", cat: "servicos", tag: "Específico", resumo: "Regimes diferenciados para imóveis. Impacto em incorporadoras e locação." },
  { id: 19, nome: "Veículos Novos", cat: "comercio", tag: "IS + padrão", resumo: "Possível incidência de Imposto Seletivo em veículos poluentes. Crédito amplo." },
  { id: 20, nome: "Produtor Rural", cat: "agro", tag: "Redução / zero", resumo: "Insumos agropecuários com alíquota zero. Produtor pessoa física com redução de 60%." },
  { id: 21, nome: "Laboratório de Análises Clínicas", cat: "saude", tag: "Redução 60%", resumo: "Serviços de saúde com redução. Crédito sobre reagentes e equipamentos." },
  { id: 22, nome: "Hospitais e Clínicas Cirúrgicas", cat: "saude", tag: "Redução 60%", resumo: "Grande benefício com redução de 60%. Gestão de créditos de insumos hospitalares." },
  { id: 23, nome: "Construtoras e Incorporadoras", cat: "industria", tag: "Específico", resumo: "Regimes para construção e imóveis. Fim de benefícios de ICMS e migração para destino." },
  { id: 24, nome: "Agência de Marketing Digital", cat: "servicos", tag: "Padrão", resumo: "Serviços digitais na alíquota padrão. Split payment e crédito sobre ferramentas e mídia." },
  { id: 25, nome: "Indústria Têxtil e Confecções", cat: "industria", tag: "Padrão", resumo: "Cadeia longa com crédito amplo. Fim da guerra fiscal impacta localização." },
  { id: 26, nome: "Agências de Turismo", cat: "servicos", tag: "Turismo", resumo: "Pacotes e intermediação. Tributação no destino e regras para plataformas." },
  { id: 27, nome: "Indústria de Pescado e Camarão", cat: "agro", tag: "Alíquota zero", resumo: "Produtos da cesta básica / insumos aquícolas com tratamento diferenciado." },
  { id: 28, nome: "Atacadista de Bebidas", cat: "comercio", tag: "Monofásico / IS", resumo: "Bebidas alcoólicas com regime monofásico e possível IS. Impacto na margem." },
  { id: 29, nome: "Provedor de Internet", cat: "servicos", tag: "Específico", resumo: "Regras específicas na LC 227/2026. Telecomunicações e regime monofásico possível." },
  { id: 30, nome: "Desenvolvedores de Software", cat: "servicos", tag: "Digital", resumo: "Software e SaaS. Tributação no destino. Crédito sobre infraestrutura e serviços." },
  { id: 31, nome: "Sucata e Reciclagem", cat: "industria", tag: "Específico", resumo: "Regras específicas na LC 227/2026 para sucata e reciclagem." },
  { id: 32, nome: "Farmácias de Manipulação", cat: "saude", tag: "Misto", resumo: "Medicamentos manipulados e insumos. Possível enquadramento em reduções de saúde." },
  { id: 33, nome: "Clínicas Veterinárias", cat: "saude", tag: "Padrão", resumo: "Serviços veterinários na alíquota padrão. Crédito sobre medicamentos e materiais." },
  { id: 34, nome: "Transportadora e Logística", cat: "servicos", tag: "Padrão", resumo: "Frete e logística. Crédito sobre combustível e manutenção. Princípio do destino." },
  { id: 35, nome: "Setor de Energia Elétrica", cat: "industria", tag: "Monofásico", resumo: "Regime monofásico para energia. Impacto estrutural na cadeia de consumo." },
  { id: 36, nome: "Clínica de Estética", cat: "servicos", tag: "Padrão", resumo: "Procedimentos estéticos. Distinção possível em relação a serviços de saúde." },
  { id: 37, nome: "Revenda de Pneus", cat: "comercio", tag: "Impacto alto", resumo: "Margens apertadas. Fim do monofásico/ST. Necessidade de reajuste e foco em serviços." },
  { id: 38, nome: "Locação de Bens Móveis", cat: "servicos", tag: "Específico", resumo: "Regras específicas na LC 227/2026 para locação de bens móveis." },
  { id: 39, nome: "Distribuidoras de Medicamentos", cat: "comercio", tag: "Misto", resumo: "Cadeia farmacêutica. Alíquota zero e reduções em medicamentos. Crédito amplo." },
  { id: 40, nome: "Indústria de Laticínios e Derivados", cat: "agro", tag: "Cesta básica", resumo: "Leite e derivados da cesta básica com alíquota zero. Benefício expressivo." },
  { id: 41, nome: "Indústria de Panificação e Confeitaria", cat: "agro", tag: "Cesta básica", resumo: "Pães e produtos da cesta básica. Tratamento diferenciado e crédito sobre insumos." },
  { id: 42, nome: "Indústria de Sucos e Bebidas Não Alcoólicas", cat: "industria", tag: "Padrão / redução", resumo: "Alguns produtos com redução. Demais na alíquota padrão com crédito." },
  { id: 43, nome: "Indústria de Rações e Alimentos Pet", cat: "agro", tag: "Padrão", resumo: "Rações e pet food. Crédito sobre insumos agrícolas e energia." },
  { id: 44, nome: "Indústria de Massas e Cereais", cat: "agro", tag: "Cesta básica", resumo: "Massas e cereais da cesta básica com alíquota zero ou redução." },
  { id: 45, nome: "Distribuidoras de Alimentos", cat: "comercio", tag: "Cesta básica", resumo: "Mix de produtos com alíquota zero e redução. Gestão de crédito e classificação fiscal." },
  { id: 46, nome: "Indústria de Bebidas", cat: "industria", tag: "IS / monofásico", resumo: "Bebidas alcoólicas com monofásico e possível IS. Impacto elevado." },
  { id: 47, nome: "Indústria de Carne e Frango", cat: "agro", tag: "Alíquota zero", resumo: "Carnes in natura com alíquota zero. Um dos setores mais beneficiados." },
  { id: 48, nome: "Setor Hortifruti", cat: "agro", tag: "Alíquota zero", resumo: "Hortifruti da cesta básica com alíquota zero. Benefício direto ao produtor e varejo." },
  { id: 49, nome: "Cemitério e Funerária", cat: "servicos", tag: "Padrão", resumo: "Serviços funerários na alíquota padrão. Crédito sobre insumos e manutenção." },
  { id: 50, nome: "Padaria e Confeitaria Varejista", cat: "comercio", tag: "Cesta básica", resumo: "Pães e produtos básicos com alíquota zero. Impacto positivo no varejo de panificação." },
  { id: 51, nome: "Comércio Varejista em Geral (Extra)", cat: "comercio", tag: "Extra", resumo: "Visão geral do comércio varejista. Estratégias de adaptação ao IVA dual." },
  { id: 52, nome: "Setor de Serviços em Geral (Extra)", cat: "servicos", tag: "Extra", resumo: "Panorama dos serviços. Reduções de 30% e 60% e impacto no Simples." },
  { id: 53, nome: "Setor Industrial em Geral (Extra)", cat: "industria", tag: "Extra", resumo: "Indústria e crédito pleno. Fim da guerra fiscal e princípio do destino." }
];